/**
 * Ordered outline for lesson sidebar + “Up next” (rule keys must exist in RULES).
 *
 * Each lesson has a dedicated file at lessons/<rule>.html (generated by scripts/generate-lesson-pages.js).
 * Optional override:
 *   page: 'path/to/other.html'  — rare; otherwise getLessonUrl uses lessons/<rule>.html
 * Optional per unit:
 *   unitLabelAr — Arabic unit name (shown in lesson sidebar next to unitLabel; also on course home nav).
 * Optional per lesson:
 *   titleAr — Arabic lesson title; if omitted, `findLessonInOutline` uses `RULES.arabicTitle` (when `app.js` loaded) or `RULE_ARABIC_TITLE`.
 * Arabic lesson titles also live in app.js → RULES[rule].arabicTitle (course home hydrates rows via course-home-arabic.js).
 */
window.COURSE_OUTLINE = [
  {
    unitId: 'unit-1',
    unitLabel: 'Unit 1 — Foundations',
    unitLabelAr: 'الْمَقْدِمَاتُ',
    lessons: [
      { rule: 'intro', title: 'Grammar rules — welcome' },
      { rule: 'kalimaat', title: 'Kalimaat — three word types' },
    ],
  },
  {
    unitId: 'unit-2',
    unitLabel: 'Unit 2 — The noun',
    unitLabelAr: 'الْإِسْم',
    lessons: [
      { rule: 'noun', title: 'The noun — overview' },
      { rule: 'gender', title: 'Gender' },
      { rule: 'gender-masc', title: 'Masculine' },
      { rule: 'gender-fem', title: 'Feminine' },
      { rule: 'number', title: 'Number' },
      { rule: 'number-singular', title: 'Singular' },
      { rule: 'number-dual', title: 'Dual' },
      { rule: 'number-plural', title: 'Plural' },
      { rule: 'vocab-body-parts', title: 'Body parts vocabulary' },
      { rule: 'idafah', title: 'Iḍāfah' },
      { rule: 'tawabi', title: 'Tawābiʿ (followers)' },
      { rule: 'naat', title: 'Naʿt (adjective)' },
      { rule: 'sifah-mawsuf', title: 'Ṣifah & mawṣūf' },
      { rule: 'atf', title: 'ʿAṭf (conjunction)' },
      { rule: 'special-nouns', title: 'Special nouns — overview' },
      { rule: 'demonstratives', title: 'Demonstratives' },
      { rule: 'relative-nouns', title: 'Relative noun (mawṣūl)' },
      { rule: 'silah-mawsul', title: 'Ṣilah of mawṣūl' },
      { rule: 'interrogative-nouns', title: 'Interrogative nouns' },
      { rule: 'magnified-nouns', title: 'Magnified nouns' },
      { rule: 'definite-indefinite', title: 'Definite & indefinite' },
      { rule: 'mabni-muarab', title: 'Mabnī & muʿrab — noun endings' },
      { rule: 'mamnu-sarf', title: 'Mamnūʿ min al-ṣarf' },
      { rule: 'masdar', title: 'Maṣdar (verbal noun)' },
      { rule: 'pronouns', title: 'Pronouns — overview' },
      { rule: 'detached-pronouns', title: 'Detached pronouns' },
      { rule: 'attached-pronouns', title: 'Attached pronouns' },
      { rule: 'attached-nouns', title: 'Pronouns with nouns' },
      { rule: 'attached-verbs', title: 'Pronouns with verbs' },
    ],
  },
  {
    unitId: 'unit-3',
    unitLabel: 'Unit 3 — The verb',
    unitLabelAr: 'الْفِعْل',
    lessons: [
      { rule: 'verb', title: 'The verb — overview' },
      { rule: 'verb-past', title: 'Past tense — overview' },
      { rule: 'verb-past-passive', title: 'Past passive' },
      { rule: 'verb-mudaaf', title: 'Geminate verb (mudāʿaf)' },
      { rule: 'verb-mahmuz', title: 'Verb with hamza' },
      { rule: 'verb-ajwaf-wawi', title: 'Hollow verb — wāw' },
      { rule: 'verb-ajwaf-yaee', title: 'Hollow verb — yāʾ' },
      { rule: 'verb-ajwaf-exception', title: 'Hollow verbs — exceptions' },
      { rule: 'verb-initial-waw', title: 'Initial wāw (assimilated)' },
      { rule: 'verb-naqis-wawi', title: 'Defective verb — wāw' },
      { rule: 'verb-present', title: 'Present / future — overview' },
      { rule: 'verb-present-passive', title: 'Present passive' },
      { rule: 'verb-present-negation', title: 'Negation & prohibition' },
      { rule: 'verb-present-conditional-particles', title: 'Conditional particles' },
      { rule: 'verb-present-jussive-particles', title: 'Jussive particles' },
      { rule: 'verb-present-nasb-particles', title: 'Accusative particles' },
      { rule: 'verb-present-double-emphasis', title: 'Lām al-tawkīd' },
      { rule: 'verb-imperative', title: 'Imperative' },
      { rule: 'verb-imperative-li', title: 'Lām al-amr (لِـ)' },
    ],
  },
  {
    unitId: 'unit-4',
    unitLabel: 'Unit 4 — Particles',
    unitLabelAr: 'الْحُرُوف',
    lessons: [
      { rule: 'harf', title: 'Particle — overview' },
      { rule: 'harf-letters', title: 'Letters of the alphabet' },
      { rule: 'harf-maani', title: 'Particles with meaning' },
      { rule: 'harf-jarr', title: 'Prepositions (jar)' },
      { rule: 'munada', title: 'Vocative (munādā)' },
    ],
  },
  {
    unitId: 'unit-5',
    unitLabel: 'Unit 5 — The sentence',
    unitLabelAr: 'الْجُمْلَة',
    lessons: [
      { rule: 'sentence-structure', title: 'Sentence structure' },
      { rule: 'nominal-sentence', title: 'Nominal sentence' },
      { rule: 'inna-sisters', title: 'Inna & sisters' },
      { rule: 'kaana-sisters', title: 'Kāna & sisters' },
      { rule: 'verbal-sentence', title: 'Verbal sentence' },
      { rule: 'fael', title: 'Faʿil (subject)' },
      { rule: 'mafool', title: 'Mafʿūl (object)' },
      { rule: 'verb-passive-overview', title: 'Passive verb — overview' },
      { rule: 'istithna', title: 'Istithnāʾ (exception)' },
    ],
  },
  {
    unitId: 'unit-6',
    unitLabel: 'Unit 6 — Iʿrāb',
    unitLabelAr: 'الْإِعْرَاب',
    lessons: [
      { rule: 'irab', title: 'Iʿrāb — overview' },
      { rule: 'irab-raf', title: 'Rafʿ — overview' },
      { rule: 'irab-raf-dammah', title: 'Rafʿ — dammah' },
      { rule: 'irab-raf-waw', title: 'Rafʿ — wāw' },
      { rule: 'irab-raf-alif', title: 'Rafʿ — alif' },
      { rule: 'irab-raf-noon', title: 'Rafʿ — nūn' },
      { rule: 'irab-nasb', title: 'Naṣb' },
      { rule: 'irab-jarr', title: 'Jarr' },
      { rule: 'irab-jazm', title: 'Jazm' },
    ],
  },
];

/**
 * Arabic lesson titles (mirror `app.js` `RULES.arabicTitle`). Used when `app.js` is not loaded
 * (e.g. Qurʾān Iʿrāb). When `window.RULES` exists, `findLessonInOutline` prefers that for `titleAr`.
 */
window.RULE_ARABIC_TITLE = {
  "atf": "الْعَطْف",
  "attached-nouns": "ضَمَائِر مُتَّصِلَة مَعَ الْأَسْمَاء",
  "attached-pronouns": "ضَمَائِر مُتَّصِلَة",
  "attached-verbs": "ضَمَائِر مُتَّصِلَة مَعَ الْأَفْعَال",
  "definite-indefinite": "نَكِرَة وَ مَعْرِفَة",
  "demonstratives": "أَسْمَاءُ الْإِشَارَة",
  "detached-pronouns": "ضَمَائِر مُنْفَصِلَة",
  "fael": "الْفَاعِل / اسْمُ الْفَاعِل",
  "gender": "الْجِنْس",
  "gender-fem": "مُؤَنَّث",
  "gender-masc": "مُذَكَّر",
  "harf": "الْحَرْف",
  "harf-jarr": "حُرُوفُ الْجَرِّ",
  "harf-letters": "حُرُوفُ الْهِجَاء",
  "harf-maani": "حُرُوفُ الْمَعَانِي",
  "idafah": "الْإِضَافَة",
  "inna-sisters": "إِنَّ وَ أَخَوَاتُهَا",
  "interrogative-nouns": "أَسْمَاءُ الِاسْتِفْهَام",
  "intro": "قواعد النحو",
  "irab": "الْإِعْرَاب",
  "irab-jarr": "الْجَرُّ",
  "irab-jazm": "الْجَزْمُ",
  "irab-nasb": "النَّصْبُ",
  "irab-raf": "الرَّفْعُ",
  "irab-raf-alif": "الْأَلِفُ",
  "irab-raf-dammah": "الضَّمَّةُ",
  "irab-raf-noon": "النُّونُ",
  "irab-raf-waw": "الْوَاوُ",
  "istithna": "الْإِسْتِثْنَاء",
  "kaana-sisters": "كَانَ وَ أَخَوَاتُهَا",
  "kalimaat": "كَلِمَات / اَلْكَلَام",
  "mabni-muarab": "الْمَبْنِي وَالْمُعْرَبُ · الْأَسْمَاءُ الْمَبْنِيَّةُ وَالْمُعْرَبَةُ",
  "mafool": "الْمَفْعُول / اسْمُ الْمَفْعُول",
  "magnified-nouns": "الْأَسْمَاءُ الْمُكَبَّرَة · الْأَسْمَاءُ الْخَمْسَة",
  "mamnu-sarf": "الْمَمْنُوعُ مِنَ الصَّرْف",
  "masdar": "الْمَصْدَر",
  "munada": "الْمُنَادَى",
  "naat": "النَّعْت",
  "nominal-sentence": "الْجُمْلَة الْإِسْمِيَّة",
  "noun": "الْإِسْم",
  "number": "الْعَدَد",
  "number-dual": "مُثَنًّى",
  "number-plural": "جَمْع",
  "number-singular": "مُفْرَد",
  "pronouns": "ضَمَائِر",
  "relative-nouns": "اسْمُ الْمَوْصُول",
  "sentence-structure": "الْجُمْلَة",
  "sifah-mawsuf": "الصِّفَةُ وَالْمَوْصُوفُ",
  "silah-mawsul": "صِلَة الْمَوْصُول",
  "special-nouns": "أَسْمَاء خَاصَّة",
  "tawabi": "التوابع",
  "verb": "الْفِعْل",
  "verb-ajwaf-exception": "الْأَجْوَفُ — اسْتِثْنَاءَاتٌ",
  "verb-ajwaf-wawi": "الْفِعْلُ الْأَجْوَفُ الْوَاوِيُ",
  "verb-ajwaf-yaee": "الْفِعْلُ الْأَجْوَفُ الْيَائِيُ",
  "verb-imperative": "فِعْلُ الْأَمْر",
  "verb-imperative-li": "لَامُ الْأَمْر",
  "verb-initial-waw": "الْفِعْلُ الْمِثَالُ (الْوَاوِيُ)",
  "verb-mahmuz": "الْفِعْلُ الْمَهْمُوزُ",
  "verb-mudaaf": "الْفِعْلُ الْمُضَاعَفُ",
  "verb-naqis-wawi": "الْفِعْلُ النَّاقِصُ الْوَاوِيُ",
  "verb-passive-overview": "الْفِعْلُ الْمَجْهُول",
  "verb-past": "الْمَاضِي",
  "verb-past-passive": "الْمَاضِي الْمَجْهُول",
  "verb-present": "الْمُضَارِع",
  "verb-present-conditional-particles": "حُرُوفُ الشَّرْط",
  "verb-present-double-emphasis": "لَامُ التَّوْكِيدِ وَ النُّونُ الثَّقِيلَةُ",
  "verb-present-jussive-particles": "حُرُوفٌ جَازِمَة",
  "verb-present-nasb-particles": "حُرُوفٌ نَاصِبَة",
  "verb-present-negation": "نَفْيُ وَ نَهْيُ الْمُضَارِعِ",
  "verb-present-passive": "الْمُضَارِعُ الْمَجْهُولُ",
  "verbal-sentence": "الْجُمْلَة الْفِعْلِيَّة",
  "vocab-body-parts": "مُفْرَدَاتُ الْجَسَد",
  "words": "كَلِمَات / اَلْكَلَام",
};

/**
 * Href for a lesson row (custom page or default query-string lesson).
 * @param {{ rule: string, page?: string }} lesson
 */
window.getLessonUrl = function getLessonUrl(lesson) {
  if (!lesson || !lesson.rule) return 'index.html';
  if (lesson.page) return lesson.page;
  return `lessons/${lesson.rule}.html`;
};

/**
 * Find outline row by rule id (includes unitLabel from parent unit).
 * @param {string} ruleId
 * @returns {{ rule: string, title: string, titleAr: string, page?: string, unitId: string, unitLabel: string, unitLabelAr: string } | null}
 */
window.findLessonInOutline = function findLessonInOutline(ruleId) {
  for (let u = 0; u < window.COURSE_OUTLINE.length; u++) {
    const unit = window.COURSE_OUTLINE[u];
    for (let i = 0; i < unit.lessons.length; i++) {
      const l = unit.lessons[i];
      if (l.rule === ruleId) {
        const fromRules =
          typeof window.RULES !== 'undefined' &&
          window.RULES[l.rule] &&
          window.RULES[l.rule].arabicTitle
            ? String(window.RULES[l.rule].arabicTitle)
            : '';
        const fromStatic =
          window.RULE_ARABIC_TITLE && window.RULE_ARABIC_TITLE[l.rule]
            ? String(window.RULE_ARABIC_TITLE[l.rule])
            : '';
        const titleAr =
          (l.titleAr && String(l.titleAr).trim()) || fromRules || fromStatic || '';
        return {
          rule: l.rule,
          title: l.title,
          titleAr,
          page: l.page || `lessons/${l.rule}.html`,
          unitId: unit.unitId,
          unitLabel: unit.unitLabel,
          unitLabelAr: unit.unitLabelAr || '',
        };
      }
    }
  }
  return null;
};

/** Arabic lesson title for a rule (empty if unknown). */
window.getLessonArabicTitle = function getLessonArabicTitle(ruleId) {
  const row = window.findLessonInOutline(ruleId);
  return row && row.titleAr ? row.titleAr : '';
};
